### ISSUE TITLE
InvalidName error while the name is valid for c++filt

### ISSUE THREAD

**Issue by jeandet** [afg984/python-cxxfilt#5]
Hi thanks for this awesome lib!

I have one issue with the following symbol:
'_ZN7QObject7connectIM7QActionFvbEZN19MesonProjectManager8Internal19MesonActionsManagerC4EvEUlvE_EENSt9enable_ifIXeqsrN9QtPrivate15FunctionPointerIT0_EE13ArgumentCountLin1EEN11QMetaObject10ConnectionEE4typeEPKNSA_IT_E6ObjectESH_PKS_SB_N2Qt14ConnectionTypeE'

with c++filt I get:
```
c++filt -i  '_ZN7QObject7connectIM7QActionFvbEZN19MesonProjectManager8Internal19MesonActionsManagerC4EvEUlvE_EENSt9enable_ifIXeqsrN9QtPrivate15FunctionPointerIT0_EE13ArgumentCountLin1EEN11QMetaObject10ConnectionEE4typeEPKNSA_IT_E6ObjectESH_PKS_SB_N2Qt14ConnectionTypeE'
std::enable_if<QtPrivate::FunctionPointer<MesonProjectManager::Internal::MesonActionsManager::MesonActionsManager()::{lambda()#1}>::ArgumentCount==(-1), QMetaObject::Connection>::type QObject::connect<void (QAction::*)(bool), MesonProjectManager::Internal::MesonActionsManager::MesonActionsManager()::{lambda()#1}>(QtPrivate<void (QAction::*)(bool)>::Object const*, std::enable_if<QtPrivate::FunctionPointer<MesonProjectManager::Internal::MesonActionsManager::MesonActionsManager()::{lambda()#1}>::ArgumentCount==(-1), QMetaObject::Connection>::type, QObject const*, QtPrivate::FunctionPointer, Qt::ConnectionType)
```

While with cxxfilt 0.2.1:
```
InvalidName                               Traceback (most recent call last)
<ipython-input-4-96b230c9969f> in <module>
----> 1 cxxfilt.demangle('_ZN7QObject7connectIM7QActionFvbEZN19MesonProjectManager8Internal19MesonActionsManagerC4EvEUlvE_EENSt9enable_ifIXeqsrN9QtPrivate15FunctionPointerIT0_EE13ArgumentCountLin1EEN11QMetaObject10ConnectionEE4typeEPKNSA_IT_E6ObjectESH_PKS_SB_N2Qt14ConnectionTypeE')

~/.local/lib/python3.8/site-packages/cxxfilt/__init__.py in demangle(mangled_name, external_only)
     75 
     76 def demangle(mangled_name, external_only=True):
---> 77     return demangleb(
     78         mangled_name.encode(), external_only=external_only).decode()

~/.local/lib/python3.8/site-packages/cxxfilt/__init__.py in demangleb(mangled_name, external_only)
     67         raise InternalError('A memory allocation failiure occurred')
     68     elif status.value == -2:
---> 69         raise InvalidName(mangled_name)
     70     elif status.value == -3:
     71         raise InternalError('One of the arguments is invalid')

InvalidName: b'_ZN7QObject7connectIM7QActionFvbEZN19MesonProjectManager8Internal19MesonActionsManagerC4EvEUlvE_EENSt9enable_ifIXeqsrN9QtPrivate15FunctionPointerIT0_EE13ArgumentCountLin1EEN11QMetaObject10ConnectionEE4typeEPKNSA_IT_E6ObjectESH_PKS_SB_N2Qt14ConnectionTypeE'
```

**Comment by afq984** [comment]
Could you provide your `cxxfilt.libcxx`?
I find that libc++ and libstdc++ behaves differently on this input.

**Comment by jeandet** [comment]
```<CDLL 'libc++.so.1', handle 5573d2a57d00 at 0x7f854fc17a90>```

then:
```
libcxx-10.0.0-1.fc32.x86_64 : C++ standard library targeting C++11
Repo        : @System
Matched from:
Filename    : /usr/lib64/libc++.so.1
```

**Comment by atlas0fd00m** [comment]
i'm having similar issues, and the behavior changed within the last year.  i thought it was a library thing with ubuntu 20.04, but my 18.04 machine no longer works correctly either.

```In [11]: cxxfilt.libcxx
Out[11]: <CDLL 'libc++.so.1', handle 558507559080 at 7f0ca4e03150>
```

when i change the code to use libbfd.cplus_demangle, the decodes work again. 
it looks like `c++filt` uses that as well.

thoughts?
does it make sense to use `cplus_demangle` instead of `__cxa_demangle`?  
i honestly don't have an opinion, i just want something that's stable and works well.

**Comment by atlas0fd00m** [comment]
nm.  simpler fix, @afq984 .

i just discovered that `libc++.so.1` doesn't seem to be as good as `libstdc++.so.6`  can we reverse the order?  i just had an app install libc++ as a dependency.  so if they're both present, `libstdc++.so.6` should win, from what i'm seeing.

i'm happy to provide a PR, or you can just reverse their order and commit.
is there any reason *not* to reverse their lookup order?

**Comment by afq984** [comment]
I think libstdc++ would be closer to c++filt (GNU binutils), so I've merged the PR.

However, I think it would be nice to let the user override the __cxa_demangle implementation. 
Maybe `from cxxfilt import Demangler; cxxfilt = Demangler('libc++')`.

**Comment by atlas0fd00m** [comment]
that makes sense to me.  i would have them hand in either a libname (which would need to be clearly documented in the docstring and readme), or a constant like `DMGL_LLVM` and `DMGL_GNU` or something like that.  if you let them hand in a string, it could simply be either prepended on the list to look up, or replace the list, making it fail if that provided library doesn't exist.  my gut says that latter one is best, letting them know it failed, instead of silently choosing another library.  or that could be an option as well.  or better yet, allow them to hand in a list of library string names.  it all depends on how flexible you want the tool to be.

but this recent merge fixes my need.  how long do you think before this makes it into pypi?

**Comment by atlas0fd00m** [comment]
in another delta i tried before realizing this was the problem, i found libbfd and used cplus_demangle().  but the Itanium ABI docs specifically state that __cxa_demangle is *the* official function for demangling.

**Comment by afq984** [comment]
I'll bump a release on pypi in a few days. You can use git+https:// if you're in a hurry.

**Comment by afq984** [comment]
@atlas0fd00m I've released 0.2.2 on pypi.

**Comment by atlas0fd00m** [comment]
thanks for the headsup! :+1:

**Comment by skyreflectedinmirrors** [comment]
> 
> 
> I think libstdc++ would be closer to c++filt (GNU binutils), so I've merged the PR.
> 
> However, I think it would be nice to let the user override the __cxa_demangle implementation.
> Maybe `from cxxfilt import Demangler; cxxfilt = Demangler('libc++')`.

@afq984, love this library, thanks for your efforts.

If it's easy to implement something like this, it would be super useful.  I have a LLVM build in a non-standard path (coming from ROCm, which places everything in /opt/rocm/llvm/*), and I find the llvm-cxxfilt we provide can handle some names that regular c++filt cannot (expected, since the compiler is llvm 😄 ).
